stages:
- run

docs:make:
  stage: run
  image: svek/pydda
  script:
    - cd docs && make dirhtml
  artifacts:
    paths:
      - docs/_build/

docs:deploy:
  # TODO: Change to a specialized image
  stage: run
  image: svenk/latex
  needs:
    - job: "docs:make"
      artifacts: true
  script:
    - chmod 600 "$STAGING_HOST_SSH_PRIVATE_KEY" "$STAGING_HOST_SSH_HOST_IDENT"
    - cd docs/_build && echo -e "cd anabrid.dev/docs/lucipy\nput -R ." | sftp -o "UserKnownHostsFile=$STAGING_HOST_SSH_HOST_IDENT" -i"$STAGING_HOST_SSH_PRIVATE_KEY" $STAGING_HOST_SSH

tests:
  stage: run
  image: svek/pydda
  script:
    - make test
