# from https://github.com/marketplace/actions/sphinx-to-github-pages

name: Build and Deploy Sphinx docs to Github Pages

on:
  push:
    branches: [master]

jobs:
  pages:
    runs-on: ubuntu-20.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
    - id: install_deps
      run: pip install nbsphinx
    - id: deployment
      uses: sphinx-notes/pages@v3
